#!/usr/bin/env bash
#
# staging-54.sh — runs ONLY §5.4 of the staging verifier:
#   * TARGET_ID is a clean UUID
#   * anon direct SELECT * on athletes blocked
#   * get_public_athlete_profile RPC returns safe column whitelist
#   * get_public_athlete_highlights RPC works or returns empty cleanly
#
# Credentials are cached in .staging-creds.env (gitignored). First run
# prompts; subsequent runs are zero-paste.
#
# Usage:
#   bash scripts/staging-54.sh             # normal run
#   bash scripts/staging-54.sh --reset     # forget cached creds, reprompt

set -u

RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
CREDS_FILE="$(dirname "$0")/../.staging-creds.env"
STAGING_REF="rwtsznxfdfgkswvgwypw"

PASS_COUNT=0; FAIL_COUNT=0; FAIL_LIST=()
pass() { echo "${GREEN}✓ PASS — $1${RESET}"; PASS_COUNT=$((PASS_COUNT+1)); }
fail() { echo "${RED}✗ FAIL — $1${RESET}"; FAIL_COUNT=$((FAIL_COUNT+1)); FAIL_LIST+=("$1"); }

if [ "${1:-}" = "--reset" ]; then
  rm -f "$CREDS_FILE"
  echo "Cleared $CREDS_FILE."
fi

# ── Load or collect credentials ────────────────────────────────────
if [ -f "$CREDS_FILE" ]; then
  # shellcheck disable=SC1090
  source "$CREDS_FILE"
  echo "Using cached credentials from $CREDS_FILE."
else
  echo "First-run setup. For each prompt, paste the value (hidden) and press Enter."
  echo

  printf "  1/3  ANON key (starts with eyJ...):  "
  IFS= read -rs ANON_KEY; echo "[hidden, ${#ANON_KEY} chars]"
  printf "  2/3  SERVICE_ROLE key (also eyJ...):  "
  IFS= read -rs SERVICE_KEY; echo "[hidden, ${#SERVICE_KEY} chars]"
  printf "  3/3  Full DB URI from dashboard (postgresql://...) — leave \\[YOUR-PASSWORD\\] literal:  "
  IFS= read -rs DB_URL_INPUT; echo "[hidden, ${#DB_URL_INPUT} chars]"

  if [[ "$DB_URL_INPUT" == *"[YOUR-PASSWORD]"* ]]; then
    printf "       DB password:  "
    IFS= read -rs DB_PW; echo "[hidden, ${#DB_PW} chars]"
    if command -v jq >/dev/null 2>&1; then
      DB_PW_ENC="$(printf '%s' "$DB_PW" | jq -sRr @uri)"
    else
      DB_PW_ENC="$DB_PW"
    fi
    DB_URL_INPUT="${DB_URL_INPUT//\[YOUR-PASSWORD\]/$DB_PW_ENC}"
  fi

  # Sanity checks
  [[ "$ANON_KEY"    == eyJ* && "${#ANON_KEY}"    -ge 100 ]] || { echo "${RED}ANON_KEY looks wrong.${RESET}"; exit 2; }
  [[ "$SERVICE_KEY" == eyJ* && "${#SERVICE_KEY}" -ge 100 ]] || { echo "${RED}SERVICE_KEY looks wrong.${RESET}"; exit 2; }
  [[ "$DB_URL_INPUT" == postgresql://* ]] || { echo "${RED}DB URI must start with postgresql://${RESET}"; exit 2; }

  # Save to gitignored file with safe permissions
  umask 077
  cat > "$CREDS_FILE" <<EOF
# Auto-generated by scripts/staging-54.sh. DO NOT COMMIT.
# Gitignored in .gitignore. Re-run with --reset to clear.
PROJECT_URL='https://${STAGING_REF}.supabase.co'
ANON_KEY='$ANON_KEY'
SERVICE_KEY='$SERVICE_KEY'
DB_URL='$DB_URL_INPUT'
EOF
  chmod 600 "$CREDS_FILE"
  echo "Saved credentials to $CREDS_FILE (mode 600, gitignored)."
  echo
  # shellcheck disable=SC1090
  source "$CREDS_FILE"
fi

if [ -z "${PROJECT_URL:-}" ] || [ -z "${ANON_KEY:-}" ] || [ -z "${DB_URL:-}" ]; then
  echo "${RED}Credentials file is missing keys. Re-run with --reset.${RESET}"
  exit 2
fi

# ── §5.4 only ──────────────────────────────────────────────────────
echo "${BOLD}═══ §5.4 ONLY — anon attack + RPC whitelist ═══${RESET}"
echo

# (1) Get TARGET_ID — strict UUID-only capture
psql_uuid() {
  psql "$DB_URL" -At -q -c "$1" 2>/dev/null \
    | awk 'BEGIN{IGNORECASE=1} /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/ { print; exit }'
}

TARGET_ID="$(psql_uuid "
  select p.id from profiles p
  join athletes a on a.user_id = p.id
  where p.role='athlete' limit 1;")"

CREATED_THROWAWAY=false
if [ -z "$TARGET_ID" ]; then
  echo "${YELLOW}No athlete in DB. Creating throwaway test athlete with sensitive fields...${RESET}"
  ORG_ID="$(psql_uuid "select id from organizations limit 1;")"
  if [ -z "$ORG_ID" ]; then
    ORG_ID="$(psql_uuid "insert into organizations (name, slug)
                         values ('Verify Test Org', 'verify-test-org-$RANDOM')
                         returning id;")"
  fi
  echo "  ORG_ID=$ORG_ID"
  TARGET_ID="$(psql_uuid "select gen_random_uuid();")"

  # Each statement runs independently and reports its own error. We DO
  # NOT silence stderr — a silent failure here is exactly how we ended
  # up with an empty RPC result for an "existing" athlete on the last
  # run. UPSERT (DO UPDATE) wins over any Supabase auth trigger that
  # may have auto-created a profile row with role='user'.
  echo "  Step 1/3: inserting auth.users row"
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "
    insert into auth.users (id, instance_id, aud, role, email, encrypted_password,
                            email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data)
    values ('$TARGET_ID',
            '00000000-0000-0000-0000-000000000000',
            'authenticated',
            'authenticated',
            'verify-athlete-$RANDOM@local.test',
            crypt('throwaway-pw-only-for-test', gen_salt('bf')),
            now(), now(), now(),
            '{\"provider\":\"email\"}'::jsonb, '{}'::jsonb)
    on conflict (id) do nothing;
  " 2>&1 | sed 's/^/    /'

  echo "  Step 2/3: upserting profiles row"
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "
    insert into profiles (id, full_name, role, org_id)
    values ('$TARGET_ID', 'Verify Athlete', 'athlete', '$ORG_ID')
    on conflict (id) do update
      set role    = excluded.role,
          org_id  = excluded.org_id,
          full_name = excluded.full_name;
  " 2>&1 | sed 's/^/    /'

  echo "  Step 3/3: upserting athletes row"
  # Column corrections: athletes.weight (not weight_kg). athletes.org_id
  # is NOT NULL — must be supplied. sat_score, act_score, intended_major
  # are added via the 010_athlete_profile_fields.sql ALTERs; they exist
  # in any environment that's run up to migration 010+.
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "
    insert into athletes (user_id, org_id, position, class_year, gpa,
                          sat_score, act_score, height_cm, weight, intended_major)
    values ('$TARGET_ID', '$ORG_ID', 'Forward', 2027, 3.95,
            1450, 32, 168, 60, 'Computer Science')
    on conflict (user_id) do update
      set org_id        = excluded.org_id,
          position      = excluded.position,
          class_year    = excluded.class_year,
          gpa           = excluded.gpa,
          sat_score     = excluded.sat_score,
          act_score     = excluded.act_score,
          height_cm     = excluded.height_cm,
          weight        = excluded.weight,
          intended_major = excluded.intended_major;
  " 2>&1 | sed 's/^/    /'

  CREATED_THROWAWAY=true
fi

# Hard guard
if ! [[ "$TARGET_ID" =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]; then
  fail "TARGET_ID is not a clean UUID. Got: '$TARGET_ID'"
  echo "${RED}Bailing — refuse to send polluted UUID into curl.${RESET}"
  exit 1
fi
pass "TARGET_ID is a clean UUID: $TARGET_ID"

# Fixture sanity: confirm the rows the RPC needs actually landed.
# If any row is missing or has the wrong role/org, the RPC will return
# [] — we surface that here rather than blaming the RPC for it.
echo
echo "${BOLD}Fixture sanity check${RESET}"
FIXTURE="$(psql "$DB_URL" -At -q -c "
  select 'auth.users   : ' || coalesce((select id::text from auth.users where id = '$TARGET_ID'), '<missing>');
  select 'profiles     : ' || coalesce((select id || '  role=' || role || '  org_id=' || org_id::text
                                          from profiles where id = '$TARGET_ID'), '<missing>');
  select 'athletes     : ' || coalesce((select user_id::text from athletes where user_id = '$TARGET_ID'), '<missing>');
  select 'organizations: ' || coalesce((select id || '  name=' || name from organizations where id = (select org_id from profiles where id = '$TARGET_ID')), '<missing>');
" 2>&1)"
echo "$FIXTURE" | sed 's/^/  /'
if echo "$FIXTURE" | grep -q '<missing>'; then
  fail "Fixture incomplete — RPC will return [] regardless of column whitelist"
fi
if ! echo "$FIXTURE" | grep -q "role=athlete"; then
  fail "Fixture profiles row exists but role is NOT 'athlete' — RPC will return []"
fi

# (2) Anon direct SELECT blocked
echo
echo "${BOLD}Test A — anon direct SELECT * on athletes${RESET}"
RESP_A="$(curl -sS -w '\n%{http_code}' \
  "$PROJECT_URL/rest/v1/athletes?select=*&user_id=eq.$TARGET_ID" \
  -H "apikey: $ANON_KEY")"
STATUS_A="$(printf '%s\n' "$RESP_A" | tail -n1)"
BODY_A="$(printf '%s\n' "$RESP_A" | sed '$d')"
echo "  HTTP $STATUS_A"
echo "  body: ${BODY_A:-(empty)}"

case "$STATUS_A" in
  401|403|404) pass "Anon SELECT blocked at HTTP layer (status $STATUS_A)" ;;
  200)
    if [ -z "$BODY_A" ] || [ "$BODY_A" = "[]" ]; then
      pass "Anon SELECT returned no rows (RLS filtered)"
    elif [[ "$BODY_A" == *"\"gpa\""* ]] || [[ "$BODY_A" == *"\"height_cm\""* ]] || [[ "$BODY_A" == *"\"sat_score\""* ]]; then
      fail "CRITICAL: anon CAN read GPA/height/SAT (HTTP 200, body $BODY_A)"
    else
      fail "Unexpected 200 response: $BODY_A"
    fi
    ;;
  *) fail "Unexpected HTTP status $STATUS_A from anon SELECT" ;;
esac

# (3) RPC get_public_athlete_profile — safe column whitelist
echo
echo "${BOLD}Test C — get_public_athlete_profile RPC${RESET}"
RPC_BODY_C="$(printf '{"p_profile_id":"%s"}' "$TARGET_ID")"
echo "  body: $RPC_BODY_C"
PROBE_C="$(printf '%s' "$RPC_BODY_C" | curl -sS -w '\n%{http_code}' \
  -X POST "$PROJECT_URL/rest/v1/rpc/get_public_athlete_profile" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  --data-binary @-)"
STATUS_C="$(printf '%s\n' "$PROBE_C" | tail -n1)"
RPC_C="$(printf '%s\n' "$PROBE_C" | sed '$d')"
echo "  HTTP $STATUS_C"
echo "$RPC_C" | jq '.[0] // .' 2>/dev/null || echo "$RPC_C"

if [ "$STATUS_C" != "200" ]; then
  fail "get_public_athlete_profile returned HTTP $STATUS_C (body $RPC_C)"
else
  KEYS_C="$(echo "$RPC_C" | jq -r '.[0] | keys[]' 2>/dev/null | sort)"
  echo "  returned columns:"; echo "$KEYS_C" | sed 's/^/    /'

  FORBIDDEN=(height_cm gpa sat_score act_score weight weight_kg intended_major)
  LEAK=""
  for c in "${FORBIDDEN[@]}"; do
    grep -qx "$c" <<<"$KEYS_C" && LEAK="$LEAK $c"
  done
  if [ -n "$LEAK" ]; then
    fail "CRITICAL: RPC leaks private columns:$LEAK"
  elif [ -z "$KEYS_C" ]; then
    fail "RPC returned no data for $TARGET_ID"
  else
    pass "RPC column whitelist clean (no GPA / SAT / ACT / height / weight / major)"
  fi
fi

# (4) RPC get_public_athlete_highlights
echo
echo "${BOLD}Test D — get_public_athlete_highlights RPC${RESET}"
RPC_BODY_D="$(printf '{"p_athlete_id":"%s"}' "$TARGET_ID")"
echo "  body: $RPC_BODY_D"
PROBE_D="$(printf '%s' "$RPC_BODY_D" | curl -sS -w '\n%{http_code}' \
  -X POST "$PROJECT_URL/rest/v1/rpc/get_public_athlete_highlights" \
  -H "apikey: $ANON_KEY" \
  -H "Authorization: Bearer $ANON_KEY" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  --data-binary @-)"
STATUS_D="$(printf '%s\n' "$PROBE_D" | tail -n1)"
RPC_D="$(printf '%s\n' "$PROBE_D" | sed '$d')"
echo "  HTTP $STATUS_D"
echo "$RPC_D" | jq '.[0] // "no clips"' 2>/dev/null || echo "$RPC_D"

if [ "$STATUS_D" = "200" ] && { [ "$RPC_D" = "[]" ] || [[ "$RPC_D" == *"mux_playback_id"* ]]; }; then
  pass "get_public_athlete_highlights returns expected shape (or empty)"
else
  fail "get_public_athlete_highlights unexpected (HTTP $STATUS_D body $RPC_D)"
fi

# Cleanup throwaway athlete if we created one
if $CREATED_THROWAWAY; then
  psql "$DB_URL" -q -c "
    delete from athletes where user_id = '$TARGET_ID';
    delete from profiles where id = '$TARGET_ID';
    delete from auth.users where id = '$TARGET_ID';
  " >/dev/null 2>&1
fi

# ── Summary ────────────────────────────────────────────────────────
echo
echo "${BOLD}─────────────────────────────${RESET}"
echo "Passes:   ${GREEN}$PASS_COUNT${RESET}"
echo "Failures: ${RED}$FAIL_COUNT${RESET}"
if [ "$FAIL_COUNT" -eq 0 ]; then
  echo "${GREEN}${BOLD}§5.4 PASSED.${RESET}"
  exit 0
else
  echo "${RED}${BOLD}§5.4 FAILED:${RESET}"
  for f in "${FAIL_LIST[@]}"; do echo "  - $f"; done
  exit 1
fi
