"""Generates supabase/football/110_seed_schools.sql from scripts/data/football-*-2026.json."""
import json, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
REGION = {}
for r, states in {
    'Pacific Northwest': 'WA OR ID AK',
    'California': 'CA HI',
    'Southwest': 'AZ NM NV TX OK',
    'Mountain West': 'CO UT WY MT',
    'Midwest': 'OH MI IN IL WI MN IA MO KS NE ND SD',
    'Northeast': 'NY PA MA CT RI NH VT ME',
    'Mid-Atlantic': 'NJ DE MD DC VA WV',
    'Southeast': 'FL GA AL MS LA AR TN SC NC KY',
}.items():
    for s in states.split(): REGION[s] = r
def q(v):
    if v is None or v == '': return 'NULL'
    if isinstance(v, (int, float)): return str(int(v))
    return "'" + str(v).replace("'", "''") + "'"
rows = []
for f in ['football-fbs-2026.json', 'football-fcs-2026.json']:
    rows += json.load(open(root / 'scripts' / 'data' / f))
names = [r['name'] for r in rows]
assert len(names) == len(set(names)), 'duplicate names'
vals = []
for r in rows:
    region = 'Ivy League' if r['conference'] == 'Ivy League' else REGION[r['state']]
    vals.append('(' + ', '.join([q(r['name']), q(r['short_name']), "'D1'", q(r['subdivision']), q(r['conference']),
        q(r['state']), q(r['city']), q(region), q(r.get('primary_color')), q(r.get('secondary_color')),
        q(r.get('athletics_website')), q(r.get('football_roster_url')), q(r.get('email_domain')),
        q(r.get('enrollment')), q(r.get('academic_rank'))]) + ')')
sql = f"""-- 110_seed_schools.sql — {len(rows)} NCAA Division I football programs (2026 season)
-- Generated by scripts/football/build-school-seed.py. Conference membership verified
-- against 2026 conference listings; enrollment, rank, colors and URLs are approximate.
INSERT INTO public.schools (name, short_name, division, subdivision, conference, state, city, region,
  primary_color, secondary_color, athletics_website, football_roster_url, email_domain, enrollment, academic_rank)
VALUES
""" + ',\n'.join(vals) + """
ON CONFLICT (name) DO UPDATE SET
  short_name = EXCLUDED.short_name, division = EXCLUDED.division, subdivision = EXCLUDED.subdivision,
  conference = EXCLUDED.conference, state = EXCLUDED.state, city = EXCLUDED.city, region = EXCLUDED.region,
  primary_color = EXCLUDED.primary_color, secondary_color = EXCLUDED.secondary_color,
  athletics_website = EXCLUDED.athletics_website, football_roster_url = EXCLUDED.football_roster_url,
  email_domain = EXCLUDED.email_domain, enrollment = EXCLUDED.enrollment, academic_rank = EXCLUDED.academic_rank;
"""
(root / 'supabase' / 'football' / '110_seed_schools.sql').write_text(sql)
print(len(rows), 'schools')
