"""Builds supabase/schema_football_v1.sql from the inherited soccer migrations
plus supabase/football/*.sql. Run from the repo root: python3 scripts/football/build-schema.py"""
import pathlib, re
root = pathlib.Path(__file__).resolve().parents[2]
mig = root / 'supabase' / 'migrations'
SKIP = {
  '013_coach_finder_seed.sql',      # soccer schools/coaches seed
  '017_coach_real_data.sql',        # soccer coach data
  '031_fix_pipeline_stages.sql',    # never apply (known-bad)
  '033_cleanup_duplicate_schools.sql',  # soccer data cleanup
  '045_public_profile_privacy.sql', # superseded by 048
  '050_backfill_profile_emails.sql',# one-time backfill; replaced by trigger
}
ORG = 'b0000000-0000-0000-0000-000000000001'
def patch(name, sql):
    sql = sql.replace('a0000000-0000-0000-0000-000000000001', ORG)
    if name == '001_create_organizations.sql':
        sql = sql.replace("'Eastside FC Washington'", "'Mercer Island High School Football'") \
                 .replace("'Eastside FC'", "'Mercer Island'").replace("'eastside-fc-wa'", "'mercer-island-hs-football'") \
                 .replace("'Seattle, WA'", "'Mercer Island, WA'").replace("'#dc2626', -- crimson", "'#8C1D40', -- maroon") \
                 .replace("'#0a1628', -- deep navy", "'#FFFFFF', -- white")
    if name == '005_create_invite_codes.sql':
        # invite codes are created in the live database, not committed
        sql = sql[:sql.index('-- Create a sample invite code')]
    return sql
parts = ['-- KRS College Connect Football - consolidated schema (generated by scripts/football/build-schema.py)\n'
         '-- Paste into a brand-new Supabase project SQL editor. Inherited soccer migrations first, football changes last.\n']
files = [f for f in sorted(mig.glob('*.sql')) if f.name not in SKIP]
files += sorted((root / 'supabase' / 'football').glob('*.sql'))
for f in files:
    parts.append(f'\n-- ============ {f.parent.name}/{f.name} ============\n' + patch(f.name, f.read_text()))
parts.append("\nNOTIFY pgrst, 'reload schema';\n")
out = root / 'supabase' / 'schema_football_v1.sql'
out.write_text(''.join(parts))
# also emit per-file chunks for incremental apply
chunks = root / 'scripts' / 'football' / '.chunks'; chunks.mkdir(exist_ok=True)
for p in chunks.glob('*'): p.unlink()
for f in files:
    (chunks / f.name).write_text(patch(f.name, f.read_text()))
print(out, len(files), 'files')
